# Programación 201

Librerías científicas en Python: `NumPy`
------------------------------------------------------

### Ejercicio 1
Calculad la norma y el determinante de la siguiente matriz: ```[[1, 0], [2, -1]]```.

In [ ]:
import numpy as np
matriz = np.array([[1,0],[2,-1]])

np.linalg.det(matriz)


-1.0

### Ejercicio 2 
Evaluad las funciones arcoseno y arcocoseno en el intervalo [0,1] y con paso (resolución) de 0.1 y guardadlas en dos _arrays_.

In [ ]:
arcocoseno = np.round(np.arccos([0,1]),1)
arcoseno = np.round(np.arcsin([0,1]),1)


### Ejercicio 3
Generad una lista de 100 valores enteros aleatorios de 0-9. Realizad los siguientes cálculos utilizando métodos de _numpy_:
- Media y desviación estándar de los valores de la lista
- Valor máximo y mínimo
- Sumad todos los valores de la lista
- Conseguid una lista de valores únicos

In [ ]:
lista = (10*np.random.random(100)).astype(int)
lista

array([5, 2, 2, 1, 7, 5, 9, 1, 7, 6, 5, 4, 1, 8, 9, 3, 9, 6, 0, 5, 3, 2,
       1, 9, 8, 2, 0, 6, 2, 6, 2, 8, 7, 8, 5, 9, 4, 3, 2, 5, 4, 7, 4, 4,
       5, 1, 6, 4, 2, 3, 3, 4, 6, 0, 3, 1, 7, 3, 0, 8, 9, 5, 6, 3, 1, 0,
       4, 9, 5, 6, 1, 8, 4, 8, 4, 0, 1, 0, 4, 6, 2, 6, 0, 3, 9, 6, 6, 6,
       4, 6, 4, 9, 0, 5, 4, 2, 0, 7, 6, 0])

In [ ]:
#media
np.mean(lista)

4.67

In [ ]:
#desviación típica
np.std(lista)

2.8497543753804466

In [ ]:
#valor máximo
np.max(lista)

9

In [ ]:
#valor mínimo
np.min(lista)

0

In [ ]:
#sumar todos los valores de la lista
sum(lista)

467

In [ ]:
#lista de valores únicos
np.unique(lista)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Ejercicio 4
Ordenad la matriz bidimensional ```[[5,1,7], [0,7,4], [7,23,1]]``` por filas utilizando como algoritmo de ordenación el [Merge sort](https://en.wikipedia.org/wiki/Merge_sort).

**Hint:** No es necesario que implementéis el algoritmo de ordenación a mano, NumPy contiene métodos para realizar diferentes tipos de ordenación sobre diferentes estructuras de datos.

In [ ]:

matriz_b = np.array([[5,1,7],[0,7,4],[7,23,1]])
matriz_b.sort(axis=-1,kind='mergesort', order= None)
print(matriz_b)

#DUDA: ¿Por qué si lo pongo todo en una fila no funciona?
#matriz_b = np.array([[5,1,7],[0,7,4],[7,23,1]]).sort(axis=-1,kind='mergesort', order= None)

[[ 1  5  7]
 [ 0  4  7]
 [ 1  7 23]]


### Ejercicio 5
Definid una función que dadas dos matrices, devuelva el valor absoluto de la multiplicación de los determinantes ambas, es decir, dadas A y B, nuestra función devolverá `|det(A) * det(B)|`.

In [ ]:
def mult_deter(A,B):
  resultado = np.linalg.det(A)*np.linalg.det(B)
  return abs(resultado)

A=np.array([[1,0],[2,-1]])
B=np.array([[1,0],[2,5]])
mult_deter(A,B)

#DUDA: No funciona lo siguiente:
#if type(A) != 'numpy.ndarray' or type(B) != 'numpy.ndarray':
#  print('Los argumentos introducidos no son matrices')

5.000000000000001

### Ejercicio 6
Cread una matriz 10x10 que corresponda con la [matriz identidad](https://es.wikipedia.org/wiki/Matriz_identidad) usando generadores básicos de arrays. Cread una matriz identidad 10x10 (esta vez usando generadores especificos de matrices identidad) y comprobad que ambas matrices son iguales

**Consideraciones**:
- La primera matriz debe crearse usando constructores básicos de arrays, como los presentados en los Notebooks de teoría.
* La segunda matriz debe generarse utilizando el generador de matrices identidad de numpy.
* La comparación debe devolver True si las matrices son iguales (un único True), False de no ser así.

In [ ]:
def matr_identidad(n):
  A=np.zeros((n,n))
  for i in range(n):
    A[i][i] = 1
  print('A =',A)    
  
  B = np.identity(n)
  print('B =',B)
  print((A == B).all())


matr_identidad(5)

A = [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
B = [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
True


### Ejercicio 7
Cread una matriz de 2x6 donde los valores de cada posición `(i, j)` correspondan a `i^2+j` para todo `i` par, `i/j^2` para todo `i` impar.

In [ ]:
for i in range(1,3):
  for j in range(1,7):
    if (i)%2 == 0:
      A[i-1][j-1] = i**2+j
    else:
      A[i-1][j-1]=i/j**2
print(A)

[[ 1.          0.25        0.11111111  0.0625      0.04        0.02777778]
 [ 5.          6.          7.          8.          9.         10.        ]]


In [ ]:
j = [1,2,3,4,5,6]
resultado = np.array([[1/n**2 for n in j],[2**2+n for n in j]])
resultado

array([[ 1.        ,  0.25      ,  0.11111111,  0.0625    ,  0.04      ,
         0.02777778],
       [ 5.        ,  6.        ,  7.        ,  8.        ,  9.        ,
        10.        ]])

### Ejercicio 8
Cread dos matrices de tamaño 5x5 con números reales aleatorios. Obtened el resultado de multiplicar ambas matrices usando los dos métodos de multiplicación de matrices vistos en el Notebook de teoría. ¿Cuál es la diferencia entre ambos resultados? Cread ahora dos matrices de tamaño 4x5 y 5x5 respectivamente, repetid la operación. Describid cuál de los métodos de multiplicación podéis aplicar y porqué

In [ ]:
A = np.random.random((5,5))
B = np.random.random((5,5))
#multiplicamos las matrices elemento por elemento:
print(A*B)
#multiplicamos matriz por matriz
print(A.dot(B))

[[0.12462072 0.04991981 0.0617125  0.67193429 0.08886364]
 [0.08897347 0.474183   0.37353964 0.14262666 0.08359237]
 [0.00658062 0.17227999 0.12325441 0.85021232 0.17209034]
 [0.55336601 0.20066955 0.10619073 0.38348729 0.08087978]
 [0.32572529 0.12800039 0.0935408  0.33887543 0.05254258]]
[[1.64112954 1.47241318 1.5212088  1.80507991 0.95142099]
 [0.7993224  1.07593289 1.2539176  1.65776761 0.63233144]
 [1.68556334 1.51671018 1.51885069 2.19776094 0.95841233]
 [1.28977347 1.08072021 1.15943513 1.56340956 0.67670317]
 [0.96250657 0.58338273 0.64929983 1.09976323 0.27509723]]


In [ ]:
A = np.random.random((4,5))
B = np.random.random((5,5))
#multiplicamos las matrices elemento por elemento, como el número de elementos en cada matriz es diferente, nos dará error:
print(A*B)
#multiplicamos matriz por matriz,  como el nºde columnas de A = nºfilas de B, no hay error
print(A.dot(B))

ValueError: ignored